### ISSUE TITLE
Relax rules regarding namespaces

### ISSUE THREAD

**Issue by beck** [yola/yophpcs#6]
Specifically:

* each class must be in a namespace
* `require` causing side-effect warnings in files that define new classes

**Comment by DevShep** [comment]
> require causing side-effect warnings in files that define new classes

The side-effect warning is about having a file that declares new symbols (classes, functions, constants, etc) with no other side effects, or files that execute logic without declaring new symbols.

I thought it was due to namespaces, but apparently not. Can you point to a sample file that was complaining about it? It might be a good thing to keep, actually.

**Comment by DevShep** [comment]
> The side-effect warning is about having a file that declares new symbols (classes, functions, constants, etc) with no other side effects, or files that execute logic without declaring new symbols.

Which is thrown on `require_once`. Damn, that's unfortunate.
